/**
 * Simple Mode Terms — Street Language (Jordanian Business Slang)
 * 
 * Used when report_mode = 'simple'
 * Conversational, warm, non-technical language for micro-business owners.
 */

export const terms_simple = {
  // ===== Navigation =====
  nav_home: 'الرئيسية',
  nav_finance: 'المالية',
  nav_orders: 'الطلبات',
  nav_settings: 'الإعدادات',
  nav_inventory: 'المخزون',

  // ===== Home Dashboard =====
  greeting_morning: 'صباح الخير',
  greeting_evening: 'مساء الخير',
  total_cash: 'إجمالي النقد المتاح',
  shop_equity: 'حق المحل',
  shop_equity_desc: 'رأس المال — للتعبئة',
  merchant_equity: 'حق التاجر',
  merchant_equity_desc: 'الأرباح — آمن للصرف',
  jars_helper: 'لا تسحب من "حق المحل" إلا لإعادة تعبئة البضاعة',
  today_income: 'قبض اليوم',
  today_expense: 'صرف اليوم',
  upcoming_orders: 'الطلبات القادمة',
  view_all: 'عرض الكل',
  quick_sale: 'بيع سريع',
  income_action: 'قبض',
  expense_action: 'صرف',
  withdrawal_action: 'سحب شخصي',
  new_order: 'طلب جديد',

  // ===== Finance Page =====
  finance_title: 'المالية',
  net_this_month: 'صافي هذا الشهر',
  total_income: 'كم قبضت',
  total_expense: 'كم صرفت',
  net_profit: 'كسبت',
  net_loss: 'خسرت',
  search_transactions: 'ابحث في المعاملات…',
  filter_all: 'الكل',
  filter_income: 'قبض',
  filter_expense: 'صرف',
  filter_withdrawal: 'سحب',
  today_label: 'اليوم',
  yesterday_label: 'أمس',
  net_for_day: 'الصافي',

  // ===== Transaction Form =====
  amount_received: 'المبلغ المستلم',
  amount_paid: 'المبلغ المدفوع',
  amount_withdrawn: 'المبلغ المسحوب',
  description: 'الوصف',
  category: 'الفئة',
  date: 'التاريخ',
  time: 'الوقت',
  save: 'حفظ',
  update: 'تحديث',
  cost_of_goods: 'تكلفة البضاعة',
  cost_of_goods_hint: 'أدخل تكلفة البضاعة لفصل رأس المال عن الربح',
  capital_jar: 'حق المحل',
  profit_jar: 'حق التاجر',
  profit_hint: 'هالصنف بتكسب منه',
  loss_warning: 'انتبه: أنت تبيع بأقل من التكلفة!',
  loss_amount: 'خسارة',
  per_piece: 'دينار على كل قطعة',
  recurring: 'التكرار',
  repeat_none: 'بدون',
  repeat_daily: 'يومي',
  repeat_weekly: 'أسبوعي',
  repeat_monthly: 'شهري',
  share_receipt: 'مشاركة إيصال واتساب',
  capital_warning_title: 'تحذير: حماية رأس المال',
  capital_warning_body: 'انتبه! أنت تسحب من رأس مال البضاعة.',
  capital_warning_explain: 'هذا السحب يتجاوز رصيد "حق التاجر" (الأرباح المتاحة للصرف). السحب من رأس المال قد يمنعك من إعادة تعبئة البضاعة.',
  profit_jar_balance: 'رصيد حق التاجر',
  withdrawal_amount: 'مبلغ السحب',
  excess_from_capital: 'الزيادة من رأس المال',

  // ===== Orders =====
  orders_title: 'الطلبات',
  list_view: 'قائمة',
  calendar_view: 'تقويم',
  search_orders: 'ابحث عن طلب…',
  status_all: 'الكل',
  status_in_progress: 'قيد التنفيذ',
  status_ready: 'جاهز',
  status_closed: 'مغلق',
  customer_name: 'اسم الزبون',
  customer_phone: 'رقم الهاتف',
  order_type: 'نوع الطلب',
  order_amount: 'المبلغ',
  order_status: 'الحالة',
  notes: 'ملاحظات',
  edit: 'تعديل',
  delete: 'حذف',
  share: 'مشاركة',
  complete_sell: 'إتمام الطلب والبيع',
  complete_sell_question: 'هل استلمت المبلغ؟',
  cash_sale: 'نعم، استلمت المبلغ نقداً',
  credit_sale: 'لا، بيع بالأجل (دين)',
  just_complete: 'مجرد إنهاء (تتبع فقط)',
  payment_cash_short: 'نقداً',
  payment_credit_short: 'أجل',
  payment_done_short: 'تتبع',
  order_value: 'قيمة الطلب',
  paid_amount: 'المدفوع',
  scheduled_time: 'الموعد',
  phone: 'الهاتف',
  call: 'اتصال',
  whatsapp: 'واتساب',
  order_details: 'تفاصيل الطلب',
  delete_order_confirm: 'اضغط للتأكيد - سيتم حذف الطلب نهائياً',
  change_status: 'تغيير الحالة',

  // ===== Debts =====
  debts_title: 'الديون',
  receivables_tab: 'لهم عندي',
  payables_tab: 'عندي لهم',
  total_receivables: 'إجمالي لهم عندي',
  total_payables: 'إجمالي عندي لهم',
  add_debt_receivable: 'إضافة دين لهم عندي',
  add_debt_payable: 'إضافة دين عندي لهم',
  receivable_desc: 'زبون يشتري الآن ويدفع لاحقاً',
  payable_desc: 'مواد على الحساب من مورد',
  settle_payment: 'تسجيل دفعة',
  pay_payment: 'سداد دفعة',
  payment_amount: 'مبلغ الدفعة',
  debt_total: 'الإجمالي',
  debt_paid: 'المدفوع',
  debt_remaining: 'المتبقي',
  debt_settled: 'مسدد',
  debt_partial: 'جزئي',
  debt_unpaid: 'غير مسدد',
  send_reminder: 'تذكير',
  payment_history: 'سجل الدفعات',

  // ===== Reports =====
  reports_title: 'التقارير',
  report_earned: 'في هالفترة كسبت',
  report_profit_label: 'ربح صافي',
  report_loss_label: 'خسارة — راجع مصاريفك',
  report_received: 'قبضت',
  report_spent: 'صرفت',
  report_daily_sales: 'مبيعات يومية',
  report_best_day: 'أفضل يوم مبيعاً كان يوم',
  report_debtors: 'عندهم فلوس لك',
  report_owes: 'عليه',
  report_send_reminder: 'تذكير',
  report_total_orders: 'إجمالي الطلبات',
  report_completed_orders: 'طلبات مكتملة',
  report_switch_to_pro: 'تغيير إلى عرض احترافي من الإعدادات',
  report_period: 'الفترة',
  report_cash_received: 'النقد المستلم',
  report_operational_expenses: 'كم صرفت على المحل',
  report_personal_withdrawal: 'سحب شخصي',
  report_net_cash_profit: 'صافي الربح النقدي',
  report_theoretical_revenue: 'إيرادات الطلبات المكتملة',
  report_theoretical_cost: 'تكلفة المواد',
  report_theoretical_profit: 'الربح المتوقع',
  report_variance: 'الفرق بين النقدي والنظري',
  report_variance_surplus: 'فائض',
  report_variance_shortage: 'عجز',
  report_variance_balanced: 'متطابق',
  report_variance_surplus_desc: 'دفعات معلقة (ديون لم تُحصّل)',
  report_variance_shortage_desc: 'تحصيل زائد (دفعات مقدمة)',
  report_variance_balanced_desc: 'متوازن',

  // ===== Settings =====
  settings_title: 'الإعدادات',
  data_management: 'إدارة البيانات',
  backup: 'نسخة احتياطية',
  backup_desc: 'تصدير البيانات إلى ملف',
  restore: 'استعادة من نسخة',
  restore_desc: 'استيراد البيانات من ملف',
  appearance: 'المظهر',
  branding: 'شعار واسم النشاط',
  branding_desc: 'رفع شعار واسم المتجر',
  whatsapp_section: 'واتساب',
  whatsapp_template: 'قالب رسالة الطلب',
  whatsapp_template_desc: 'تخصيص الرسالة المرسلة للزبون',
  operations_security: 'التشغيل والأمان',
  security_section: 'الأمان',
  auto_lock: 'القفل التلقائي',
  auto_lock_desc: 'إقفال التطبيق بعد فترة من عدم الاستخدام',
  auto_lock_off: 'معطّل',
  auto_lock_30s: '30 ثانية',
  auto_lock_1m: 'دقيقة',
  auto_lock_5m: '5 دقائق',
  hide_amounts: 'إخفاء المبالغ عند الفتح',
  hide_amounts_desc: 'إخفاء الأرقام المالية حتى يتم إدخال رمز PIN',
  display_section: 'العرض',
  font_size: 'حجم الخط',
  font_size_desc: 'عادي أو كبير لراحة القراءة',
  font_size_normal: 'عادي',
  font_size_large: 'كبير',
  list_density: 'كثافة القوائم',
  list_density_desc: 'مريحة أو مضغوطة',
  list_density_comfortable: 'مريحة',
  list_density_compact: 'مضغوطة',
  fiscal_year_start: 'بداية السنة المالية',
  fiscal_year_start_desc: 'الشهر الذي تبدأ فيه سنتك المحاسبية',
  monthly_summary: 'ملخص شهري',
  monthly_summary_desc: 'تقرير مصغّر في نهاية كل شهر',
  show_quick_pos: 'إظهار شاشة البيع السريع',
  show_quick_pos_desc: 'بيع منتجات بضغطة واحدة',
  helper_mode: 'تفعيل وضع المساعد',
  helper_mode_desc: 'وضع محدود للموظفين (بيع فقط)',
  helper_mode_pin_label: 'أدخل رمز PIN (4 أرقام)',
  helper_mode_activate: 'تفعيل ودخول وضع المساعد',
  helper_mode_active: 'وضع المساعد مُفعّل',
  helper_mode_active_desc: 'اضغط الزر بالأعلى للدخول للوضع الآن',
  enter_helper_mode: 'الدخول لوضع المساعد الآن',
  enter_helper_mode_desc: 'تفعيل الوضع المحدود فوراً',
  closing_time: 'وقت إقفال اليومية',
  closing_time_desc: 'وقت تذكير بإقفال الصندوق',
  report_display: 'عرض التقارير',
  report_mode_simple: 'بسيطة',
  report_mode_pro: 'احترافية',
  report_mode_desc: 'بسيطة (بطاقات) أو احترافية (جداول)',
  app_section: 'التطبيق',
  notifications: 'تفعيل تذكيرات الطلبات',
  notifications_desc: 'إشعارات قبل موعد الطلبات',
  install_instructions: 'كيفية تثبيت التطبيق',
  install_desc: 'تعليمات الإضافة للشاشة الرئيسية',
  install_already_done: 'التطبيق مُثبَّت',
  install_already_done_desc: 'أنت تستخدم التطبيق كتطبيق أصلي. يعمل بدون إنترنت.',
  install_ready: 'التطبيق جاهز للتثبيت',
  install_ready_desc: 'اضغط الزر أدناه لإضافة التطبيق إلى شاشتك الرئيسية.',
  install_button: 'تثبيت التطبيق',
  install_success: 'تم بدء التثبيت. ستجد الأيقونة على شاشتك الرئيسية.',
  install_dismissed: 'تم إلغاء التثبيت. يمكنك المحاولة لاحقاً.',
  install_failed: 'تعذّر التثبيت. جرّب التعليمات اليدوية أدناه.',
  install_manual: 'تثبيت يدوي',
  install_manual_desc: 'متصفحك لا يدعم التثبيت بنقرة واحدة. اتبع التعليمات أدناه.',
  install_android_title: 'على Android (Chrome):',
  install_android_step1: 'افتح قائمة المتصفح (⋮) في الأعلى',
  install_android_step2: 'اختر "إضافة إلى الشاشة الرئيسية"',
  install_android_step3: 'اضغط "تثبيت"',
  install_android_step4: 'سيظهر التطبيق كأيقونة على هاتفك',
  install_ios_title: 'على iPhone (Safari):',
  install_ios_step1: 'اضغط زر المشاركة (□↑) في الأسفل',
  install_ios_step2: 'اختر "إضافة إلى الشاشة الرئيسية"',
  install_ios_step3: 'اضغط "إضافة"',
  install_ios_step4: 'سيظهر التطبيق كأيقونة على هاتفك',
  install_offline_note: 'بعد التثبيت، يعمل التطبيق بدون إنترنت تماماً مثل التطبيقات الأصلية',
  factory_reset_warning: 'تحذير: حذف نهائي',
  factory_reset_warning_desc: 'سيتم مسح كل المعاملات والطلبات والديون والإعدادات نهائياً. لا يمكن التراجع عن هذا الإجراء.',
  factory_reset_type_label: 'للتأكيد، اكتب كلمة',
  factory_reset_placeholder: 'اكتب هنا…',
  factory_reset_type_hint: 'يجب أن تطابق تماماً كلمة "حذف" ليُتاح الزر.',
  factory_reset_confirm: 'حذف كل البيانات نهائياً',
  about_app: 'حول التطبيق',
  factory_reset: 'حذف جميع البيانات',
  factory_reset_desc: 'إعادة التطبيق للحالة الأولى',

  // ===== Empty States =====
  empty_no_transactions: 'بداية موفقة! سجل أول بيعة',
  empty_no_transactions_search: 'لم نلاقي نتائج، جرب كلمة ثانية',
  empty_no_orders: 'ما في طلبات بعد، أضف أول طلب',
  empty_no_debts_receivable: 'ما حدا عليك، كلها مخلصة',
  empty_no_debts_payable: 'ما عليك شي، كلها مخلصة',
  empty_no_data: 'لسه ما في بيانات',
  empty_no_products: 'ما في منتجات سريعة، أضف منتجاتك الأكثر مبيعاً',
  empty_no_orders_calendar: 'ما في طلبات بهذا اليوم',

  // ===== Onboarding =====
  onboarding_welcome: 'أهلاً بك',
  onboarding_subtitle: 'تطبيق بسيط لإدارة محاسبتك وطلباتك. لنبدأ في أقل من دقيقة!',
  onboarding_shop_name: 'اسم متجرك',
  onboarding_shop_name_placeholder: 'متجري',
  onboarding_start: 'ابدأ الآن',
  onboarding_skip: 'تخطي (استخدام "متجري")',
  onboarding_ready: 'جاهز!',
  onboarding_ready_desc: 'ابدأ بتسجيل أول عملية بيع...',

  // Onboarding — layer intent (V13)
  onboarding_layer_title: 'كيف تريد استخدام التطبيق؟',
  onboarding_layer_subtitle: 'اختر الوضع اللي يناسبك. تقدر تغيّره لاحقاً من الإعدادات.',
  onboarding_layer_daily_title: 'البسيط',
  onboarding_layer_daily_desc: 'مبيعات سريعة + مخزون يدوي + تقارير بسيطة',
  onboarding_layer_manager_title: 'المتوسط',
  onboarding_layer_manager_desc: 'مخزون تنبؤي + خصم تلقائي (BOM) + رادار هامش الربح',
  onboarding_layer_investor_title: 'المتقدم',
  onboarding_layer_investor_desc: 'لوحة تنفيذية + أصول/قروض/رأس مال + تصدير PDF',
  onboarding_layer_skip: 'تخطّي (يومي)',

  // Settings — layer switcher reassurance (V13)
  layer_switch_safe: 'تبديل الوضع لا يحذف بياناتك',
  opening_balance_title: 'أدخل رصيدك الحالي',
  opening_balance_desc: 'أدخل رصيدك الحالي لبدء الحساب بدقة. يمكنك القيام بذلك لاحقاً.',
  opening_balance_enter: 'إدخال الرصيد',
  opening_balance_later: 'لاحقاً',
  opening_balance_amount: 'النقد المتاح',

  // ===== Z-Report =====
  z_report_title: 'إقفال اليومية',
  z_report_expected: 'النقد المتوقع في الصندوق',
  z_report_counted: 'النقد الفعلي الذي عده التاجر',
  z_report_variance: 'الفرق بين المتوقع والفعلي',
  z_report_save: 'حفظ الإقفال',
  z_report_reminder: 'حان وقت إقفال اليوم',
  z_report_reminder_desc: 'اضغط هنا لعد النقد ومطابقته مع السجلات',

  // ===== Backup Reminder =====
  backup_reminder_title: 'حماية بياناتك',
  backup_reminder_desc: 'لحماية بياناتك، اضغط هنا لإرسال نسخة احتياطية لنفسك عبر واتساب',
  backup_send: 'إرسال نسخة احتياطية عبر واتساب',

  // ===== Add Sheet =====
  add_new: 'إضافة جديدة',
  income_desc: 'استلام مبلغ',
  expense_desc: 'دفع مبلغ',
  withdrawal_desc: 'لا يؤثر على الربح',
  order_desc: 'إضافة طلب زبون',

  // ===== POS =====
  pos_title: 'البيع السريع',
  pos_cart: 'السلة',
  pos_clear: 'مسح',
  pos_total: 'الإجمالي',
  pos_complete_sale: 'إتمام البيع',
  pos_payment_method: 'كيف تم الاستلام؟',
  pos_cash: 'نقداً (كاش)',
  pos_credit: 'بالأجل (دين)',
  pos_sale_success: 'تم البيع بنجاح',
  pos_sale_recorded: 'تم تسجيل البيع',
  pos_product_name: 'اسم المنتج',
  pos_selling_price: 'سعر البيع',
  pos_cost_price: 'سعر الشراء',
  pos_add_product: 'منتج جديد',
  pos_edit_product: 'تعديل منتج',
  pos_delete_product: 'حذف منتج',
  pos_delete_confirm: 'هل تريد حذف',

  // ===== Snackbar =====
  undo: 'تراجع',
  snackbar_deleted: 'تم حذف المعاملة',
  snackbar_saved: 'تم الحفظ بنجاح',
  snackbar_order_saved: 'تم حفظ الطلب',
  snackbar_debt_saved: 'تم تسجيل الدين',
  snackbar_settlement_saved: 'تم تسجيل الدفعة',
  snackbar_closing_saved: 'تم حفظ الإقفال',
  snackbar_backup_sent: 'تم إرسال النسخة الاحتياطية عبر واتساب',
  snackbar_reminder_sent: 'تم إرسال تذكير واتساب',

  // ===== Overview (V14 — /overview executive panel) =====
  overview_chip_label: 'نظرة عامة',
  overview_title: 'نظرة عامة',
  overview_layer_badge_prefix: 'وضعك: ',
  overview_layer_daily: 'البسيط',
  overview_layer_manager: 'المتوسط',
  overview_layer_investor: 'المتقدم',
  overview_range_today: 'اليوم',
  overview_range_week: 'الأسبوع',
  overview_range_month: 'الشهر',
  overview_back: 'رجوع',
  overview_hero_label_layer_1: 'صافي الأسبوع',
  overview_hero_label_layer_2: 'صافي + هامش',
  overview_hero_label_layer_3: 'صافي / حقوق الملكية',
  overview_hero_margin: 'هامش {value}%',
  overview_hero_equity_ratio: '{value}% من حق المحل',
  overview_kpi_revenue: 'الإيرادات',
  overview_kpi_expense: 'المصاريف',
  overview_kpi_profit: 'الصافي',
  overview_kpi_margin: 'الهامش',
  overview_kpi_cash: 'النقد',
  overview_kpi_inventory: 'المخزون',
  overview_kpi_restock: 'إعادة طلب',
  overview_kpi_roi: 'العائد على الاستثمار',
  overview_kpi_equity: 'حقوق الملكية',
  overview_analysis_section_title: 'تحليل',
  overview_strategic_actions_title: 'إجراءات استراتيجية',
  overview_add_asset: 'إضافة أصل',
  overview_add_loan: 'إضافة قرض',
  overview_inject_capital: 'حقن رأس مال',
  overview_owner_draw: 'سحب للبيت',
  overview_export_pdf: 'تصدير PDF',
  overview_analysis_week_summary: 'هذا الأسبوع ربحت {profit} وصرفت {expense}.',
  overview_analysis_no_data: 'لسه ما في بيانات كافية للتحليل.',
  overview_analysis_margin_breakdown: 'تفصيل التكاليف والهامش',
  overview_analysis_inventory_status: 'حالة المخزون',
  overview_analysis_restock_prediction: 'تنبّه إعادة الطلب',
  overview_analysis_restock_ok: 'كل الأصناف بمستويات كويسة',
  overview_analysis_restock_warn: '{count} صنف يحتاج إعادة طلب قريب',
  overview_income_statement_title: 'قائمة الدخل',
  overview_balance_sheet_title: 'الميزانية العمومية',
  overview_strategic_add_asset_desc: 'جهاز، معدات، سيارة',
  overview_strategic_add_loan_desc: 'قرض بنكي أو دين',
  overview_strategic_inject_capital_desc: 'ضخ نقود في المحل',
  overview_strategic_owner_draw_desc: 'أخذ راتب',
  overview_strategic_menu_title: 'إضافة استراتيجية',
  overview_asset_name_label: 'اسم الأصل',
  overview_asset_value_label: 'القيمة',
  overview_asset_lifespan_label: 'العمر الافتراضي (سنوات)',
  overview_asset_save: 'حفظ الأصل',
  overview_loan_name_label: 'الوصف',
  overview_loan_amount_label: 'المبلغ',
  overview_loan_type_payable: 'عليّ دين',
  overview_loan_type_receivable: 'لي دين',
  overview_loan_save: 'حفظ القرض',
  overview_capital_hint: 'أدخل المبلغ الذي تريد ضخّه في المحل. سيُضاف كدخل يزيد من النقد المتاح.',
  overview_capital_save: 'حقن رأس المال',
  overview_draw_hint: 'أدخل المبلغ الذي تريد سحبه من المحل. سيُسجّل كخصم من الأرباح.',
  overview_draw_save: 'سحب المبلغ',
  overview_assets: 'الأصول',
  overview_liabilities: 'الخصوم',
  overview_gross_profit: 'إجمالي الربح',
  overview_opex: 'مصاريف تشغيلية',
  overview_wastage: 'هدر',
  overview_net_profit: 'صافي الربح',
  overview_remaining: 'متبقي',
  overview_restock_action: 'إعادة طلب',
  overview_more_items: '+ {count} صنف آخر',

  // ===== Insights Panel — "معلومات تهمّك" (V14 — Agent 5) =====
  // Prioritized insights mounted at #overview-insights-placeholder on /overview.
  // Up to 3 cards rendered, ranked by score; layer-awareness always present.
  insights_section_title: 'معلومات تهمّك',
  insight_cloud_backup_off_title: 'لم تفعّل النسخ السحابي',
  insight_cloud_backup_off_body: 'بياناتك معرّضة للضياع — فعّل النسخ على Google Drive',
  insight_cloud_backup_off_action: 'الإعدادات',
  insight_inventory_low_title: 'مخزون ناقص',
  insight_inventory_low_body: '{count} صنف وصل للحد الأدنى',
  insight_inventory_low_action: 'المخزون',
  insight_overdue_debts_title: 'فلوس مستحقة عليهم',
  insight_overdue_debts_body: 'عندك {amount} ما تحصّلهم من سبع أيام',
  insight_overdue_debts_action: 'الديون',
  insight_no_sales_today_title: 'لسه ما بعت شي اليوم',
  insight_no_sales_today_body: 'سجّل أول بيعة عشان يبدأ يومك يطلع رقم',
  insight_layer_awareness_1: 'أنت في الوضع البسيط — سجّل المبيعات والمصاريف بسرعة. فعّل الوضع المتوسط لتتبّع التكلفة والمخزون.',
  insight_layer_awareness_2: 'أنت في الوضع المتوسط — تتابع التكلفة والمخزون. فعّل الوضع المتقدم لمتابعة الأصول والقروض وحقوق الملكية.',
  insight_layer_awareness_3: 'أنت في الوضع المتقدم — تتابع الصورة الكاملة: أصول، قروض، حقوق ملكية، العائد على الاستثمار.',
  insight_upgrade_1_to_2_title: 'مبيعاتك كبرت',
  insight_upgrade_1_to_2_body: 'فعّل الوضع المتوسط لتتبّع التكلفة وهامش الربح',
  insight_upgrade_1_to_2_action: 'فعّل المتوسط',
  insight_upgrade_2_to_3_title: 'أعمالك تنمو',
  insight_upgrade_2_to_3_body: 'فعّل الوضع المتقدم لمتابعة الأصول والقروض وحقوق الملكية',
  insight_upgrade_2_to_3_action: 'فعّل المتقدم',
  insight_downgrade_2_to_1_title: 'تبسيط الاستخدام',
  insight_downgrade_2_to_1_body: 'لم تتابع المخزون من فترة — تقدر ترجع للوضع البسيط عشان تبسّط استخدامك',
  insight_downgrade_2_to_1_action: 'رجوع للبسيط',
  insight_downgrade_3_to_2_title: 'تبسيط الاستخدام',
  insight_downgrade_3_to_2_body: 'ما سجّلت أصول ولا قروض لسه — تقدر ترجع للوضع المتوسط عشان تبسّط استخدامك',
  insight_downgrade_3_to_2_action: 'رجوع للمتوسط',
}
