/**
 * Pro Mode Terms — Formal Accounting Language
 * 
 * Used when report_mode = 'pro'
 * Professional financial terminology for users with accounting knowledge.
 */

export const terms_pro = {
  // ===== Navigation =====
  nav_home: 'الرئيسية',
  nav_finance: 'المالية',
  nav_orders: 'الطلبات',
  nav_settings: 'الإعدادات',

  // ===== Home Dashboard =====
  greeting_morning: 'صباح الخير',
  greeting_evening: 'مساء الخير',
  total_cash: 'إجمالي النقد المتاح',
  shop_equity: 'حق المحل',
  shop_equity_desc: 'رأس المال العامل — لإعادة التعبئة',
  merchant_equity: 'حق التاجر',
  merchant_equity_desc: 'صافي الأرباح — متاح للسحب',
  jars_helper: 'لا تسحب من "حق المحل" إلا لإعادة تعبئة البضاعة',
  today_income: 'القبض اليوم',
  today_expense: 'الصرف اليوم',
  upcoming_orders: 'الطلبات القادمة',
  view_all: 'عرض الكل',
  quick_sale: 'بيع سريع',
  income_action: 'قبض',
  expense_action: 'صرف',
  withdrawal_action: 'سحب شخصي',
  new_order: 'طلب جديد',

  // ===== Finance Page =====
  finance_title: 'المالية',
  net_this_month: 'صافي هذا الشهر',
  total_income: 'إجمالي الإيرادات',
  total_expense: 'إجمالي المصروفات',
  net_profit: 'صافي الربح',
  net_loss: 'صافي الخسارة',
  search_transactions: 'ابحث في القيود…',
  filter_all: 'الكل',
  filter_income: 'قبض',
  filter_expense: 'صرف',
  filter_withdrawal: 'سحب',
  today_label: 'اليوم',
  yesterday_label: 'أمس',
  net_for_day: 'الصافي',

  // ===== Transaction Form =====
  amount_received: 'المبلغ المقبوض',
  amount_paid: 'المبلغ المصروف',
  amount_withdrawn: 'المبلغ المسحوب',
  description: 'الوصف',
  category: 'الفئة',
  date: 'التاريخ',
  time: 'الوقت',
  save: 'حفظ',
  update: 'تحديث',
  cost_of_goods: 'تكلفة البضاعة المباعة',
  cost_of_goods_hint: 'أدخل تكلفة البضاعة لفصل رأس المال عن الربح',
  capital_jar: 'حق المحل',
  profit_jar: 'حق التاجر',
  profit_hint: 'هذا الصنف ربحه',
  loss_warning: 'تنبيه: سعر البيع أقل من التكلفة!',
  loss_amount: 'خسارة',
  per_piece: 'دينار لكل وحدة',
  recurring: 'التكرار',
  repeat_none: 'بدون',
  repeat_daily: 'يومي',
  repeat_weekly: 'أسبوعي',
  repeat_monthly: 'شهري',
  share_receipt: 'مشاركة إيصال واتساب',
  capital_warning_title: 'تنبيه: حماية رأس المال',
  capital_warning_body: 'انتبه! أنت تسحب من رأس مال البضاعة.',
  capital_warning_explain: 'هذا السحب يتجاوز رصيد "حق التاجر" (الأرباح المتاحة للصرف). السحب من رأس المال قد يمنعك من إعادة تعبئة البضاعة.',
  profit_jar_balance: 'رصيد حق التاجر',
  withdrawal_amount: 'مبلغ السحب',
  excess_from_capital: 'الزيادة من رأس المال',

  // ===== Orders =====
  orders_title: 'الطلبات',
  list_view: 'قائمة',
  calendar_view: 'تقويم',
  search_orders: 'ابحث عن طلب…',
  status_all: 'الكل',
  status_in_progress: 'قيد التنفيذ',
  status_ready: 'جاهز',
  status_closed: 'مغلق',
  customer_name: 'اسم الزبون',
  customer_phone: 'رقم الهاتف',
  order_type: 'نوع الطلب',
  order_amount: 'المبلغ',
  order_status: 'الحالة',
  notes: 'ملاحظات',
  edit: 'تعديل',
  delete: 'حذف',
  share: 'مشاركة',
  complete_sell: 'إتمام الطلب والبيع',
  complete_sell_question: 'هل استلمت المبلغ؟',
  cash_sale: 'نعم، استلمت المبلغ نقداً',
  credit_sale: 'لا، بيع بالأجل (دين)',
  just_complete: 'إغلاق الطلب (تتبع فقط)',
  payment_cash_short: 'نقداً',
  payment_credit_short: 'آجل',
  payment_done_short: 'تتبع',
  order_value: 'قيمة الطلب',
  paid_amount: 'المدفوع',
  scheduled_time: 'الموعد المجدول',
  phone: 'الهاتف',
  call: 'اتصال',
  whatsapp: 'واتساب',
  order_details: 'تفاصيل الطلب',
  delete_order_confirm: 'اضغط للتأكيد - سيتم حذف الطلب نهائياً',
  change_status: 'تغيير الحالة',

  // ===== Debts =====
  debts_title: 'الديون',
  receivables_tab: 'الذمم المدينة',
  payables_tab: 'الذمم الدائنة',
  total_receivables: 'إجمالي الذمم المدينة',
  total_payables: 'إجمالي الذمم الدائنة',
  add_debt_receivable: 'إضافة ذمم مدينة',
  add_debt_payable: 'إضافة ذمم دائنة',
  receivable_desc: 'بيع بالأجل — يستحق التحصيل',
  payable_desc: 'شراء بالأجل — يستحق السداد',
  settle_payment: 'تسجيل سند قبض',
  pay_payment: 'تسجيل سند صرف',
  payment_amount: 'مبلغ الدفعة',
  debt_total: 'الإجمالي',
  debt_paid: 'المسدد',
  debt_remaining: 'المتبقي',
  debt_settled: 'مسدد بالكامل',
  debt_partial: 'مسدد جزئياً',
  debt_unpaid: 'غير مسدد',
  send_reminder: 'تذكير',
  payment_history: 'سجل التسويات',

  // ===== Reports =====
  reports_title: 'التقارير',
  report_earned: 'صافي الربح للفترة',
  report_profit_label: 'ربح صافي',
  report_loss_label: 'خسارة — راجع المصروفات',
  report_received: 'الإيرادات النقدية',
  report_spent: 'المصروفات النقدية',
  report_daily_sales: 'المبيعات اليومية',
  report_best_day: 'أعلى يوم مبيعاً كان يوم',
  report_debtors: 'الذمم المدينة المستحقة',
  report_owes: 'مدين بمبلغ',
  report_send_reminder: 'تذكير',
  report_total_orders: 'إجمالي الطلبات',
  report_completed_orders: 'الطلبات المكتملة',
  report_switch_to_pro: 'تغيير إلى عرض مبسط من الإعدادات',
  report_period: 'الفترة',
  report_cash_received: 'النقد المستلم',
  report_operational_expenses: 'المصروفات التشغيلية',
  report_personal_withdrawal: 'السحب الشخصي',
  report_net_cash_profit: 'صافي الربح النقدي',
  report_theoretical_revenue: 'إيرادات الطلبات المكتملة',
  report_theoretical_cost: 'تكلفة البضاعة المباعة',
  report_theoretical_profit: 'الربح النظري المتوقع',
  report_variance: 'الفرق بين النقدي والنظري',
  report_variance_surplus: 'فائض',
  report_variance_shortage: 'عجز',
  report_variance_balanced: 'متطابق',
  report_variance_surplus_desc: 'ذمم مدينة لم تُحصّل بعد',
  report_variance_shortage_desc: 'تحصيل دفعات مقدمة',
  report_variance_balanced_desc: 'متوازن',

  // ===== Settings =====
  settings_title: 'الإعدادات',
  data_management: 'إدارة البيانات',
  backup: 'نسخة احتياطية',
  backup_desc: 'تصدير البيانات إلى ملف',
  restore: 'استعادة من نسخة',
  restore_desc: 'استيراد البيانات من ملف',
  appearance: 'المظهر',
  branding: 'شعار واسم النشاط',
  branding_desc: 'رفع شعار واسم المتجر',
  whatsapp_section: 'واتساب',
  whatsapp_template: 'قالب رسالة الطلب',
  whatsapp_template_desc: 'تخصيص الرسالة المرسلة للزبون',
  operations_security: 'التشغيل والأمان',
  security_section: 'الأمان',
  auto_lock: 'القفل التلقائي',
  auto_lock_desc: 'إقفال التطبيق بعد فترة خمول',
  auto_lock_off: 'معطّل',
  auto_lock_30s: '30 ثانية',
  auto_lock_1m: 'دقيقة',
  auto_lock_5m: '5 دقائق',
  hide_amounts: 'إخفاء المبالغ عند الفتح',
  hide_amounts_desc: 'إخفاء الأرقام المالية حتى إدخال رمز PIN',
  display_section: 'العرض',
  font_size: 'حجم الخط',
  font_size_desc: 'عادي أو كبير لراحة القراءة',
  font_size_normal: 'عادي',
  font_size_large: 'كبير',
  list_density: 'كثافة القوائم',
  list_density_desc: 'مريحة أو مضغوطة',
  list_density_comfortable: 'مريحة',
  list_density_compact: 'مضغوطة',
  fiscal_year_start: 'بداية السنة المالية',
  fiscal_year_start_desc: 'الشهر الذي يبدأ فيه العام المحاسبي',
  monthly_summary: 'ملخص شهري',
  monthly_summary_desc: 'تقرير مختصر في نهاية كل شهر',
  show_quick_pos: 'إظهار شاشة البيع السريع',
  show_quick_pos_desc: 'بيع منتجات بضغطة واحدة',
  helper_mode: 'تفعيل وضع المساعد',
  helper_mode_desc: 'وضع محدود للموظفين (بيع فقط)',
  helper_mode_pin_label: 'أدخل رمز PIN (4 أرقام)',
  helper_mode_activate: 'تفعيل ودخول وضع المساعد',
  helper_mode_active: 'وضع المساعد مُفعّل',
  helper_mode_active_desc: 'اضغط الزر بالأعلى للدخول للوضع الآن',
  enter_helper_mode: 'الدخول لوضع المساعد الآن',
  enter_helper_mode_desc: 'تفعيل الوضع المحدود فوراً',
  closing_time: 'وقت إقفال اليومية',
  closing_time_desc: 'وقت تذكير بإقفال الصندوق',
  report_display: 'عرض التقارير',
  report_mode_simple: 'مبسط',
  report_mode_pro: 'احترافي',
  report_mode_desc: 'مبسط (بطاقات) أو احترافي (جداول)',
  app_section: 'التطبيق',
  notifications: 'تفعيل تذكيرات الطلبات',
  notifications_desc: 'إشعارات قبل موعد الطلبات',
  install_instructions: 'كيفية تثبيت التطبيق',
  install_desc: 'تعليمات الإضافة للشاشة الرئيسية',
  install_already_done: 'التطبيق مُثبَّت',
  install_already_done_desc: 'أنت تستخدم التطبيق كتطبيق أصلي. يعمل بدون إنترنت.',
  install_ready: 'التطبيق جاهز للتثبيت',
  install_ready_desc: 'اضغط الزر أدناه لإضافة التطبيق إلى شاشتك الرئيسية.',
  install_button: 'تثبيت التطبيق',
  install_success: 'تم بدء التثبيت. ستجد الأيقونة على شاشتك الرئيسية.',
  install_dismissed: 'تم إلغاء التثبيت. يمكنك المحاولة لاحقاً.',
  install_failed: 'تعذّر التثبيت. جرّب التعليمات اليدوية أدناه.',
  install_manual: 'تثبيت يدوي',
  install_manual_desc: 'متصفحك لا يدعم التثبيت بنقرة واحدة. اتبع التعليمات أدناه.',
  install_android_title: 'على Android (Chrome):',
  install_android_step1: 'افتح قائمة المتصفح (⋮) في الأعلى',
  install_android_step2: 'اختر "إضافة إلى الشاشة الرئيسية"',
  install_android_step3: 'اضغط "تثبيت"',
  install_android_step4: 'سيظهر التطبيق كأيقونة على هاتفك',
  install_ios_title: 'على iPhone (Safari):',
  install_ios_step1: 'اضغط زر المشاركة (□↑) في الأسفل',
  install_ios_step2: 'اختر "إضافة إلى الشاشة الرئيسية"',
  install_ios_step3: 'اضغط "إضافة"',
  install_ios_step4: 'سيظهر التطبيق كأيقونة على هاتفك',
  install_offline_note: 'بعد التثبيت، يعمل التطبيق بدون إنترنت تماماً مثل التطبيقات الأصلية',
  factory_reset_warning: 'تحذير: حذف نهائي',
  factory_reset_warning_desc: 'سيتم مسح كل المعاملات والطلبات والديون والإعدادات نهائياً. لا يمكن التراجع عن هذا الإجراء.',
  factory_reset_type_label: 'للتأكيد، اكتب كلمة',
  factory_reset_placeholder: 'اكتب هنا…',
  factory_reset_type_hint: 'يجب أن تطابق تماماً كلمة "حذف" ليُتاح الزر.',
  factory_reset_confirm: 'حذف كل البيانات نهائياً',
  about_app: 'حول التطبيق',
  factory_reset: 'حذف جميع البيانات',
  factory_reset_desc: 'إعادة التطبيق للحالة الأولى',

  // ===== Empty States =====
  empty_no_transactions: 'لا توجد قيود مسجلة. ابدأ بتسجيل أول قيد',
  empty_no_transactions_search: 'لا توجد نتائج مطابقة لبحثك',
  empty_no_orders: 'لا توجد طلبات مسجلة. أضف أول طلب',
  empty_no_debts_receivable: 'لا توجد ذمم مدينة مستحقة',
  empty_no_debts_payable: 'لا توجد ذمم دائنة مستحقة',
  empty_no_data: 'لا توجد بيانات متاحة',
  empty_no_products: 'لا توجد منتجات سريعة. أضف منتجاتك الأكثر مبيعاً',
  empty_no_orders_calendar: 'لا توجد طلبات في هذا اليوم',

  // ===== Onboarding =====
  onboarding_welcome: 'أهلاً بك',
  onboarding_subtitle: 'تطبيق لإدارة المحاسبة والطلبات. لنبدأ في أقل من دقيقة!',
  onboarding_shop_name: 'اسم النشاط',
  onboarding_shop_name_placeholder: 'متجري',
  onboarding_start: 'ابدأ الآن',
  onboarding_skip: 'تخطي (استخدام "متجري")',
  onboarding_ready: 'تم الإعداد بنجاح!',
  onboarding_ready_desc: 'يمكنك الآن تسجيل أول عملية...',
  opening_balance_title: 'إدخال الرصيد الافتتاحي',
  opening_balance_desc: 'أدخل رصيدك الحالي لبدء الحساب بدقة. يمكنك القيام بذلك لاحقاً.',
  opening_balance_enter: 'إدخال الرصيد',
  opening_balance_later: 'لاحقاً',
  opening_balance_amount: 'النقد المتاح',

  // ===== Z-Report =====
  z_report_title: 'إقفال اليومية',
  z_report_expected: 'النقد المتوقع في الصندوق',
  z_report_counted: 'النقد الفعلي المعود',
  z_report_variance: 'الفرق بين المتوقع والفعلي',
  z_report_save: 'حفظ الإقفال',
  z_report_reminder: 'حان وقت إقفال اليوم',
  z_report_reminder_desc: 'اضغط هنا لعد النقد ومطابقته مع السجلات',

  // ===== Backup Reminder =====
  backup_reminder_title: 'حماية بياناتك',
  backup_reminder_desc: 'لحماية بياناتك، اضغط هنا لإرسال نسخة احتياطية لنفسك عبر واتساب',
  backup_send: 'إرسال نسخة احتياطية عبر واتساب',

  // ===== Add Sheet =====
  add_new: 'إضافة جديدة',
  income_desc: 'استلام مبلغ',
  expense_desc: 'دفع مبلغ',
  withdrawal_desc: 'لا يؤثر على الربح',
  order_desc: 'إضافة طلب زبون',

  // ===== POS =====
  pos_title: 'البيع السريع',
  pos_cart: 'السلة',
  pos_clear: 'مسح',
  pos_total: 'الإجمالي',
  pos_complete_sale: 'إتمام البيع',
  pos_payment_method: 'كيف تم الاستلام؟',
  pos_cash: 'نقداً (كاش)',
  pos_credit: 'بالأجل (دين)',
  pos_sale_success: 'تم تسجيل البيع بنجاح',
  pos_sale_recorded: 'تم تسجيل البيع',
  pos_product_name: 'اسم المنتج',
  pos_selling_price: 'سعر البيع',
  pos_cost_price: 'سعر الشراء',
  pos_add_product: 'منتج جديد',
  pos_edit_product: 'تعديل منتج',

  // ===== Snackbar =====
  undo: 'تراجع',
  snackbar_deleted: 'تم حذف القيد',
  snackbar_saved: 'تم الحفظ بنجاح',
  snackbar_order_saved: 'تم حفظ الطلب',
  snackbar_debt_saved: 'تم تسجيل الذمم',
  snackbar_settlement_saved: 'تم تسجيل التسوية',
  snackbar_closing_saved: 'تم حفظ الإقفال',
  snackbar_backup_sent: 'تم إرسال النسخة الاحتياطية عبر واتساب',
  snackbar_reminder_sent: 'تم إرسال تذكير واتساب',
}
